import Foundation

enum Report {
    static func printSummary(_ report: ConversionReport, csvPath: String, urlsPath: String) {
        let total = report.totalSpotify
        let matched = report.matchedISRC + report.matchedSearch
        let pct = total == 0 ? 0.0 : (Double(matched) / Double(total)) * 100.0

        print("")
        print("─── Conversion summary ───")
        print(" playlist:        \(report.playlistName)")
        print(String(format: " matched:         %d/%d (%.1f%%)", matched, total, pct))
        print("   - by ISRC:     \(report.matchedISRC)")
        print("   - by search:   \(report.matchedSearch)")
        print(" skipped (local): \(report.skippedLocal)")
        print(" unmatched:       \(report.unmatched)")
        print(" matches:         \(urlsPath)")
        print(" report:          \(csvPath)")
    }

    /// Writes one row per Spotify track with match status, Apple Music URL,
    /// and unmatched reasons. Always writes a header.
    static func writeCSV(_ rows: [MatchRow], to path: String) throws {
        var out = "spotify_id,title,artists,album,isrc,duration_ms,tier,score,apple_music_id,apple_music_url,best_candidate_title,best_candidate_artist,reason\n"
        for r in rows {
            let cells: [String] = [
                r.result.track.id,
                r.result.track.name,
                r.result.track.artists.joined(separator: "; "),
                r.result.track.albumName,
                r.result.track.isrc ?? "",
                String(r.result.track.durationMs),
                r.result.tier.rawValue,
                String(format: "%.1f", r.result.score),
                r.result.appleSongID ?? "",
                r.appleMusicURL?.absoluteString ?? "",
                r.result.bestCandidateTitle ?? "",
                r.result.bestCandidateArtist ?? "",
                r.result.reason ?? ""
            ]
            out += cells.map(csvEscape).joined(separator: ",") + "\n"
        }
        try out.data(using: .utf8)?.write(to: URL(fileURLWithPath: path), options: [.atomic])
    }

    /// One Apple Music URL per matched track. Header comment summarises the
    /// playlist and gives the user a one-paragraph instruction for using it
    /// with Music.app, since macOS doesn't let third-party tools script the
    /// final "add catalog track to playlist" step.
    static func writeURLList(_ rows: [MatchRow], playlistName: String, to path: String) throws {
        var out = "# Apple Music matches for Spotify playlist: \(playlistName)\n"
        out += "# Generated by playlist-convert. Manual final step:\n"
        out += "#   1. Open Music.app, create a new playlist.\n"
        out += "#   2. Run: xargs -I{} open '{}' < \(path) (or click links one at a time).\n"
        out += "#   3. In Music.app, click + on each loaded song, then drag into your playlist.\n"
        out += "# (macOS does not allow non-paid-developer tools to script library mutation.)\n"
        out += "\n"
        for r in rows where r.appleMusicURL != nil {
            out += r.appleMusicURL!.absoluteString + "\n"
        }
        try out.data(using: .utf8)?.write(to: URL(fileURLWithPath: path), options: [.atomic])
    }

    private static func csvEscape(_ s: String) -> String {
        if s.contains(",") || s.contains("\"") || s.contains("\n") {
            let escaped = s.replacingOccurrences(of: "\"", with: "\"\"")
            return "\"\(escaped)\""
        }
        return s
    }
}

/// Pairs a MatchResult with the resolved Apple Music URL (only present for
/// matched tracks).
struct MatchRow {
    let result: MatchResult
    let appleMusicURL: URL?
}
